# Generated by Django 5.0.7 on 2024-10-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospitalregister_delete_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalregister',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
