# Generated by Django 5.0.7 on 2024-11-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_donor_email_alter_donor_area_alter_donor_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
